### ISSUE TITLE
SHA-256 or SHA-512 when signing? 

### ISSUE THREAD

**Issue by mycognosist** [cabal-club/cable#14]
Hey friends, just wondering which hash function should be used when signing messages? sha256 or sha512?

**Comment by hackergrrl** [comment]
Great question. Are you working on an implementation? I've updated the spec to reflect these details:

https://github.com/cabal-club/cable/tree/v1-draft#42-ed25519

I've chosen SHA-512 primarily to be in alignment with what libsodium is using, since that's what we're using for the reference implementation.

**Comment by mycognosist** [comment]
Whoop! Thanks for the clarification. I really like the addition you made to the spec. I had looked around in the libsodium docs for a short while but quickly gave up the search.

> Are you working on an implementation?

Just tinkering ^_^

**Comment by hackergrrl** [comment]
Same re: the documentation. I usually end up having to [scan the source](https://github.com/jedisct1/libsodium/blob/6d566070b48efd2fa099bbe9822914455150aba9/src/libsodium/crypto_sign/ed25519/ref10/sign.c#L77).
